### ISSUE TITLE
Detect invalid branch and exit with useful error

### ISSUE THREAD

**Issue by stefan-koch-sociomantic** [sociomantic-tsunami/neptune#162]
Neptune prints the following:

```
$ neptune-release 
We are on branch v0.6.x
Detected release v0.6.0
Warning: Corresponding milestone still has 1 open issues!
List of ingored non-semver branches: []
Actions to be done:
 * Creating annotated tag v0.6.0 (git tag --cleanup=verbatim -F- v0.6.0 v0.6.x)
 * Create tracking branch v0.6.x (git branch v0.6.x v0.6.0)
 * Checkout v0.x.x locally (git checkout v0.x.x)
 * Merge v0.6.0 into v0.x.x (git merge --no-ff -m Merge tag v0.6.0 into v0.x.x v0.6.0)
 * Checkout previous branch v0.6.x (git checkout v0.6.x)
 * Removing release notes (git rm relnotes/first_release.feature.md)
 * Commiting removal of release notes (git commit -m Clear release notes after release)
 * Checkout next branch v0.x.x (git checkout v0.x.x)
 * Creating annotated tag v0.6.0 (git tag --cleanup=verbatim -F- v0.6.0 v0.x.x)
 * Create tracking branch v0.6.x (git branch v0.6.x v0.6.0)
 * Removing release notes (git rm relnotes/first_release.feature.md)
 * Commiting removal of release notes (git commit -m Clear release notes after release)
 * Checkout original branch v0.6.x (git checkout v0.6.x)

Would you like to continue? y/n: n
```

I assume this is because it's confused about being in a minor or in a major release.

**Comment by mihails-strasuns-sociomantic** [comment]
@stefan-koch-sociomantic something is wrong with your repo state. Normally with neptune-release you would create version `0.6.0` from head of `0.x.x` branch and neptune-release would branch `0.6.x` for you (so that 0.6.1 and so on can be done against it). In your case 0.6.x is already created, but 0.6.0 is missing.

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, this was accidentally run on branch `v0.6.x` instead of `v0.x.x` (and was created before the tool ran. 

Ideal neptune should refuse to run if the repo is not in a good state. I know that given that neptune works doing heuristics to figure out which version should be released, maybe is hard to detect these kind of misuses, but I think there is room for improvement, and if the tool is intended for the general public, it should eventually get more robust (we are now using it to release `dfmt`, which is a project with much more exposure than our OSS projects).

**Comment by mihails-strasuns** [comment]
Maybe we can implement separate `neptune-release --sanity-check` sub-command that checks all assumptions of a given repo and silently run that before any actual releases.

**Comment by leandro-lucarella-sociomantic** [comment]
Why wouldn't you run the sanity checks always before the release if you had those?

**Comment by mihails-strasuns-sociomantic** [comment]
You would:

> and silently run that before any actual releases

:P 

Benefit of also exposing it as a separate command is that it can be put to Travis pipeline to ensure that neptune repo always stays well-formed.

**Comment by mathias-baumann-sociomantic** [comment]
What versions did exists before you ran that?

**Comment by mathias-baumann-sociomantic** [comment]
I tried to think of a scenario that would result in a faulty detection of the release.. 

I assumed:
* the tag `v0.6.0-alpha.1` was existing at the time a
* you ran without the prerelease option
* you are on branch `v0.6.x`
* `v0.6.0` doesn't exist yet

But I still can't come up  with a scenario that wouldn't bail out with those start conditions.

**Comment by mihails-strasuns** [comment]
There was no `v0.6.0-alpha.1` or any other `v0.6` tag at all. But `v0.6.x` branch was already manually created.

**Comment by mathias-baumann-sociomantic** [comment]
Hmm so to prevent this situation, I have to add a check that a matching minor version exists for the current branch if the current branch is also a minor branch.

**Comment by leandro-lucarella-sociomantic** [comment]
Thank you! Consider yourself praised! :tada:
