### ISSUE TITLE
Build and test with the latest DMD

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/neptune#220]
This repo is only being tested with 2 very old dmd versions. Trying to build with the latest dmd v2.081 fails. I don't see any reason not to try to use the latest dmd in the travis matrix, to make sure we stay compatible.

**Comment by mihails-strasuns-sociomantic** [comment]
It is not that simple:

- To switch to latest DMD we have to switch to vibe.d 0.8.x
- vibe.d 0.8.x is split into many small sub-packages instead of single big library like 0.7.x
- To make that build with current makefile it would have to build every such sub-package as a separate static library and link all together - major increase in size and "messiness"

I think we should probably switch this repo back to using dub in all its terribleness to avoid this headache.

**Comment by leandro-lucarella-sociomantic** [comment]
Can't we just build all the small packages as a single static library (if that makes any sense)? Otherwise I'm fine with trying with `dub` again, but it let me down every time I tried :P

**Comment by mihails-strasuns-sociomantic** [comment]
I think we can but it is still something that needs to be done by hand and may break in future if packages get split further. AFAIR most dub problems came from testing and build configuration so neptune may tolerate it.

**Comment by mathias-baumann-sociomantic** [comment]
I suppose we could also enhance dub when we encounter problems?

**Comment by leandro-lucarella-sociomantic** [comment]
I think many were design/philosophical issues. But I'm still open to give it another try.

**Comment by mihails-strasuns** [comment]
Done via https://github.com/sociomantic-tsunami/neptune/pull/223
